import type { Metadata } from 'next';
import { Poppins as FontSans } from 'next/font/google';

import './globals.css';
import { cn } from '@/lib/utils';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title: 'Swap Rx',
	description: 'Generated by create next app',
};

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
	weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning={true}
			className='scroll-smooth overflow-x-hidden'
		>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable
				)}
			>
				<div className='min-h-screen flex flex-col'>
					<Header />
					{children}
					<Toaster />

					<Footer />
				</div>
			</body>
		</html>
	);
}
