import PolicyCard from '@/components/policy-card';


import type { Metadata } from 'next';


export const metadata: Metadata = {
	title: 'Swap Rx Policies',
	description: 'Generated by create next app',
};

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className='max-w-screen-xl mx-auto flex flex-col lg:grid lg:grid-cols-7 py-12 gap-8 w-full px-6 relative'>
			<PolicyCard className='col-span-full w-full lg:col-span-2 self-start h-auto lg:sticky lg:top-[100px]' />
			<aside className='col-span-5'>{children}</aside>
		</main>
	);
}
